# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RheinTech Energy - Creating A Green New World
email: info@rte-energy.de
description: > # this means to ignore newlines until "baseurl:"
  Creating A Green New World

url: "https://rheintech-energy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://www.rte-energy.de" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog

# Company Information
company_name: RheinTech Energy GmbH
address_line: Sandstr. 87, 40789 Monheim a. Rhein, Germany
telephone_number: 0049 (0) 214 314 997 0
fax_number: 0049 (0) 214 314 997 17
company_email: info@rte-energy.de
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2504.902448231176!2d6.8983799999999995!3d51.110260000000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47bf32f1a55ce0ed%3A0x483bef24cdcf3a8c!2sSandstra%C3%9Fe%2087%2C%2040789%20Monheim%20am%20Rhein!5e0!3m2!1sen!2sde!4v1684483069861!5m2!1sen!2sde
# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# languages
languages: [en, de, cn]
default_lang: de
defaults:
  - scope:
      path: en # an empty string here means all files in the project
      types: pages
    values:
      lang: en
  - scope:
      path: de
      types: pages
    values:
      lang: de
  - scope:
      path: cn
      types: pages
    values:
      lang: cn

exclude:
  - README.md
  - LICENSE
